Added 6.5 release notes
basespace/basespace-help pull request #404
Opened 2021-01-19 23:03 UTC by gmoyerbrailean

2021-01-19 23:53 UTC, whedley requested changes

2021-01-19 23:53 UTC, whedley commented on _docs/release-notes/basespace/2021/6.5.0.md
> + - Fixed an issue on the Run Metris tab where the Tbp unit was not being used for yield values above 1000 Gbp.
@gmoyerbrailean  Typo. Metrics

2021-01-19 23:55 UTC, whedley commented on _docs/release-notes/basespace/2021/6.5.0.md
> + - Improved behavior when creating a new Project in a Project Chooser modal. Creating a new Project automatically selects the and closes the modal.
Grammar. Selects **it** ?

2021-01-20 00:11 UTC, harmonj3 commented on _docs/release-notes/basespace/2021/6.5.0.md
> + - Improved behavior when creating a new Project in a Project Chooser modal. Creating a new Project automatically selects the and closes the modal.
Just delete 'the'

2021-01-20 00:14 UTC, harmonj3 approved these changes
lgtm

2021-01-20 00:14 UTC, harmonj3 approved these changes
lgtm

2021-01-20 00:14 UTC, whedley approved these changes
TLTQ

2021-01-20 00:14 UTC, gmoyerbrailean commented
Thanks @whedley good catches! Fixed.

@harmonj3 after long deliberation I decided to implement a similar fix to your suggestion. Hopefully it's okay.

2021-01-20 01:12 UTC, merged